const universityCourses = [
  "Bachelor of Science in Computer Science",
  "Software Engineering",
  "Data Science",
  "Information Technology",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Environmental Engineering",
  "Business and Management",
  "Bachelor of Business Administration (BBA)",
  "Executive MBA (EMBA)",
  "Accounting",
  "Finance",
  "Marketing",
  "Entrepreneurship",
  "Health Sciences",
  "Bachelor of Science in Nursing (BSN)",
  "Doctor of Medicine (MD)",
  "Doctor of Dental Surgery (DDS)",
  "Doctor of Pharmacy (Pharm.D)",
  "Public Health",
  "Physical Therapy",
  "Social Sciences",
  "Bachelor of Arts in Psychology",
  "Bachelor of Arts in Sociology",
  "Anthropology",
  "Economics",
  "Political Science",
  "International Relations",
  "Natural Sciences",
  "Bachelor of Science in Biology",
  "Bachelor of Science in Chemistry",
  "Physics",
  "Environmental Science",
  "Geology",
  "Astronomy",
  "Humanities",
  "Bachelor of Arts in English Literature",
  "History",
  "Philosophy",
  "Linguistics",
  "Art History",
  "Cultural Studies",
  "Education",
  "Bachelor of Education (B.Ed)",
  "Master of Education (M.Ed)",
  "Teaching Credential Programs",
  "Educational Leadership",
  "Special Education",
  "Fine Arts",
  "Bachelor of Fine Arts (BFA)",
  "Visual Arts",
  "Graphic Design",
  "Performing Arts (Theater, Dance, Music)",
  "Creative Writing",
  "Law",
  "Bachelor of Laws (LLB)",
  "Juris Doctor (JD)",
  "Master of Laws (LLM)",
  "Criminal Law",
  "Corporate Law",
  "International Law",
  "Communication and Media Studies",
  "Bachelor of Arts in Communication",
  "Journalism",
  "Public Relations",
  "Media Studies",
  "Film Studies",
  "Bachelor of Science in Information Technology",
  "Cybersecurity",
  "Network Administration",
  "Web Development",
  "IT Management",
];

export { universityCourses };
